name: CI/CD ‚Äì Micro Product Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_PROJECT_NAME: product_app
  APP_CONTAINER_NAME: product_app_2025
  SONAR_PROJECT_KEY: product-app
  SONAR_HOST_URL: http://localhost:9000
  SONAR_TOKEN: squ_2b54e5db054320f48c30ae60464d5d35d41c5326

jobs:
  build_analyze_deploy:
    runs-on: self-hosted

    steps:
      - name: üì• Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: ‚òï Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: ‚öôÔ∏è Construir el .jar con Maven
        run: mvn clean package -DskipTests

      - name: üìä An√°lisis con SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }}

      - name: üöÄ Despliegue con Docker Compose
        run: |
          echo "üîß Desplegando aplicaci√≥n..."
          cd docker
          docker-compose -p $DOCKER_PROJECT_NAME down -v --remove-orphans || true
          docker-compose -p $DOCKER_PROJECT_NAME up -d --build
          echo "üìã Logs recientes:"
          docker logs --tail 50 $APP_CONTAINER_NAME
